---

- name: Stop Apache2
  service: 
    name: apache2 
    state: stopped

- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  
- name: Create document root dir for example.com
  ansible.builtin.file:
    path: "{{ document_root }}"
    state: directory
    mode: '0755'

- name: Copy virtual hosts config file
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/{{ item }}
  loop: [example.com, flask.example.com]
  notify: Restart Nginx

- name: Create soft link
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  loop: [example.com, flask.example.com]

- name: Copy index.html to document root
  copy:
    src: index.html
    dest: "{{ document_root }}" 
    mode: preserve

- name: add example.com to hosts 
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1  {{ domainname }} flask.{{ domainname }}"

- name: Start nginx
  service: name=nginx state=started